spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: chatService
    redis:
      url: ${REDIS_URL}

server:
  port: 8080

token:
  secret: ${JWT_SECRET}
  server-ip: ${SERVER_IP}
  token-expiration: 900011
  token-refresh-expiration: 604800000

logging:
  level:
    org.springframework.security: INFO

  file:
    name: ${LOG_PATH_DEV}