spring:
  application:
    name: chatService

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  forward-headers-strategy: framework
  servlet:
    context-path: "/api/v1"

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
