spring:
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      authentication-database: admin
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      database: mapleChat
    redis:
      url: ${REDIS_URL}

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:localhost.p12
    key-store-password: wonseok
    key-store-type: PKCS12

token:
  secret: ${JWT_SECRET}
  server-ip: ${SERVER_IP}
  token-expiration: 900011
  token-refresh-expiration: 604800000

logging:
  level:
    org.springframework.security: DEBUG
