spring:
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      authentication-database: admin
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      database: mapleChat
    redis:
      url: ${REDIS_URL}

server:
  port: 8081

token:
  secret: ${JWT_SECRET}
  server-ip: ${SERVER_IP}
  token-expiration: 900011
  token-refresh-expiration: 604800000

logging:
  level:
    root: INFO
    com.mapleland.chatService: DEBUG
    org.springframework.security: WARN
    org.springframework.web.socket.config.WebSocketMessageBrokerStats: WARN
  file:
    name: ${LOG_PATH_PROD}