spring:
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      authentication-database: admin
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      database: mapleChat

token:
  secret: ${JWT_SECRET}
  server-ip: ${SERVER_IP}

logging:
  level:
    org.springframework.security: WARN
